# model config
batch_size = 10
point_batches = 500
lr = 0.001
lr_decay = 0.2
data_path = "data/raw/Coco"
total_epoch = 20

# wb config
wb_enabled = true
project_name = 'your_project_name'
entity = 'your_username'
